# Generated by Django 3.2.8 on 2022-01-20 03:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ratings_rated_by_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='rated_by_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
