# Generated by Django 3.2.8 on 2022-06-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_ratings_rated_by_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultRatingCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rc_name', models.CharField(max_length=1000)),
                ('description', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
