# Generated by Django 3.2.8 on 2022-06-06 14:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_ratingcriteria_from_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='rated_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
